#[build]
#  publish = "dist-splat2mesh"
#  command = "npm run build:splat2mesh"

[build]
  publish = "dist"
  command = "npm run build:theater"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

